# Generated by Django 5.0.2 on 2024-03-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(default=0, unique=True)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingSlot',
        ),
    ]
